name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v4
        with:
            node-version-file: ".nvmrc"

      - name: install pnpm
        run: |
          corepack enable
          corepack install

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm --filter "webassembly-playground" run build

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/webassembly-playground/dist
          publish_branch: gh-pages
